---
- hosts: localhost
  connection: local

  tasks:
    #    - name: Install required software
    #      become: true
    #      become_user: root
    #      delegate_to: 127.0.0.1
    #      ansible.builtin.shell: 
    #        cmd: "dnf install {{ item }}"
    #      loop:
    #        - podman

    - name: Start container registry
      ansible.builtin.shell:
        cmd: podman run -d -p 5000:5000 --name "$HOSTNAME-registry-c" --restart=always registry:2

    - name: Start minikube
      ansible.builtin.shell:
        cmd: minikube start --insecure-registry "host.minikube.internal:5000" --container-runtime=containerd --driver podman --cpus 4 --memory 4096 

...
